##############################
# Variables you need to change
##############################

samples: "config/samples.csv"  # name of the sample metadata CSV 
final_prefix: "" # prefix for final output files

##############################
# Variables you *might* need to change
##############################

## Filtering options ##

contig_size: 10000 # snps on contigs this size or smaller will be filtered from the final clean vcfs. Set to 0 to disable.
maf: 0.01 #snps with MAF below this value will be filtered from the final clean vcfs. Set to 0 to disable.
missingness: 0.75 #snps with missingness greater than this value will be filtered from the final clean vcfs. Set to 1 to disable.
scaffolds_to_exclude: "mtDNA,Y" #comma separated, no spaces list of scaffolds to exclude from final clean vcfs. Set to blank to disable.